### ISSUE TITLE
add example of using multiple different providers

### ISSUE THREAD

**Issue by programmerjake** [RomainMichau/ActixWeb_openIDConnect#3]
e.g. if I want to build a website that allows authentication using both GitHub and Google, can this library do that?

**Comment by RomainMichau** [comment]
This is not something common afaik.
Usually in order to achieve that, you will have a primary IDP with which your app will exclusively communicate.
And to support google/github auth you will configure an IDP federation between your primary IDP and google/github (ex: [Configuring a federation](https://medium.com/codeshakeio/configure-keycloak-to-use-google-as-an-idp-4e3c59583345) keycloak => google).

This will allow you to hide auth implementation details from your website, and configure that directly on IDP level

**Comment by programmerjake** [comment]
> This is not something common afaik.

Well, Forgejo and Gitea both seem to directly use external IDPs without an intermediate IDP, using the Go library: https://github.com/markbates/goth
